/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ShopManagerV2;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    public String getGreeting() {
        return "Welcome to the Shop Manager System Version 2.0";
    }
    

    public static void main(String[] args) {
        String url = "jdbc:postgresql://localhost:5432/ShopManager";
        String username = "ShopManager";
        String password = "7SpotPontiac";

        try{
            Connection steve = DriverManager.getConnection(url, username, password);
            Statement stevejr = steve.createStatement();
            int rowcount = stevejr.executeUpdate("insert into customers ( fname , lname , phone_number ) values ('Jeffery' , 'Lebowski' , '552-2433')");
            System.out.println(rowcount + " Rows Affected");
            

        }catch(SQLException e){
            e.printStackTrace();
        }


        int menu = 0;
        System.out.println(new App().getGreeting());

        System.out.println("Building user interface...");
        UI.buildMenu(menu);
        

    }
}
