/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ShopManagerV2;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

class AppTest {
    
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void carSQLaddscar(){
        Connection connection;
        try {
            connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ShopManager" , "ShopManager" , "7SpotPontiac");
            CarSQL SQL = new CarSQL(connection);

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        //new Car(1, "1973", "Ford" , "Gran Torino", "Doesn't Matter Man", "CA", "AB1D3");

    }
}
